### ISSUE TITLE
Tagged folders and tagged assets in untagged folders creates conflicts

### ISSUE THREAD

**Issue by OpenBagTwo** [OpenBagTwo/EnderChest#22]
## Summary

Trying to place both untagged assets inside tagged folders (intent: everything in this folder should go into this instance) and tagged assets inside untagged folders (intent: just this thing should go into this instance) results in `enderchest place` being unable to place the tagged folder, due to the prior existence of the non-symlink folder.

## Environment and Version
- Operating System: Linux (Ubuntu 22.04, kernel 6.0.9)
- Shell: bash 5.1.16
- Python: 3.10.8 | packaged by conda-forge
- EnderChest version: v0.0.4+15.g526e9a9

## Steps to Reproduce

Say I have the following EnderChest layout:

```
- global
  - mods
    - BestModEver.jar@Axolotl@Bee@Creeper
  - mods@Bee
    - JustAnOkayMod.jar
```

and say that `bee` does not already contain a `mods` folder.

Then when I run `enderchest place` I get the following error:

```
Traceback (most recent call last):
  File "/main/.mambaforge/bin/enderchest", line 33, in <module>
    sys.exit(load_entry_point('enderchest', 'console_scripts', 'enderchest')())
  File "/main/Programming/EnderChest/enderchest/cli.py", line 263, in main
    action(root, **kwargs)
  File "/main/Programming/EnderChest/enderchest/place.py", line 58, in place_enderchest
    link_server(path, servers / _tokenize_server_name(tag), asset)
  File "/main/Programming/EnderChest/enderchest/place.py", line 145, in link_server
    os.symlink(relative_path, server_file)
FileExistsError: [Errno 17] File exists: '../../EnderChest/global/mods@Bee' -> '~/minecraft/instances/Bee/mods'
```

## Workaround
1. Instead of mixing and matching, rename the file in `global/mods` to ` BestModEver.jar@Axolotl@Creeper` and then either copy or symlink it into `global/mods@Bee`
2. Temporarily remove or rename `global/mods/BestModEver.jar@Axolotl@Bee@Creeper`, then run `enderchest place` to create the symlink, then restore the mod and run `enderchest place` again. This actually has the advantage of automatically performing (1)

## Severity
Inconvenience

## Desired Outcome
Fix: Tagged folders should take priority over untagged ones.

## Urgency
Low

**Comment by OpenBagTwo** [comment]
Shulker box redesign makes the sync priority explicit. But it also may cause some funny behavior, with some shulkers placing links into other shulkers. I'm not sure if that's a bug or a feature, though.

**Comment by OpenBagTwo** [comment]
Captured better in #50
